stages:
  - deploy

variables:
  SSH_PRIVATE_KEY: $CI_PRIVATE_KEY
  DEV_REPO_PATH: /srv/nexuspro/services/auth-service

before_script:
  - 'which ssh-agent || (apk update && apk add openssh-client)'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy_dev:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no glitch@$192.168.0.13 -p 22 "cd $DEV_REPO_PATH && git pull origin dev"
    - ssh -o StrictHostKeyChecking=no glitch@$192.168.0.13 -p 22 "cd $DEV_REPO_PATH && docker compose up -d --build"
  only:
    - master
  
