version: '3'
services:
  app:
    build: .
    command: poetry run python3 -m auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus-catalog-public.rule=Host(`auth-dev-nexuspro.webdsm.kz`)"

networks:
  default:
    name: nexus-network
    external: true