version: '3'
services:
  psql:
    image: postgres
    hostname: "auth-db"
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: hackme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

  app:
    build: .
    command: poetry run python3 -m auth
    ports:
      - "8000:8000"
    networks:
      - auth-network


volumes:
  postgres_data:

networks:
  auth-network:
    name: auth-network
