"""Create User

Revision ID: 78894385c1bd
Revises: 
Create Date: 2023-08-14 11:36:19.816210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78894385c1bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
